version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db_pokemon
      - MYSQL_USER=mouny
      - MYSQL_PASSWORD=pwd
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  app:
    restart: always
    build: .
    image: webscrapping_pokemontrash
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/scrap_pokemontrash

volumes:
  db_data: {}
